// Code generated by "stringer --type CommandType --trimprefix CommandType"; DO NOT EDIT.

package commands

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogCommandTypeBoot-0]
	_ = x[LogCommandTypeReset-255]
	_ = x[CommandTypeEcho-1]
	_ = x[CommandTypeCreateSession-3]
	_ = x[CommandTypeAuthenticateSession-4]
	_ = x[CommandTypeSessionMessage-5]
	_ = x[CommandTypeDeviceInfo-6]
	_ = x[CommandTypeReset-8]
	_ = x[CommandTypeCloseSession-64]
	_ = x[CommandTypeStorageStatus-65]
	_ = x[CommandTypePutOpaque-66]
	_ = x[CommandTypeGetOpaque-67]
	_ = x[CommandTypePutAuthKey-68]
	_ = x[CommandTypePutAsymmetric-69]
	_ = x[CommandTypeGenerateAsymmetricKey-70]
	_ = x[CommandTypeSignDataPkcs1-71]
	_ = x[CommandTypeListObjects-72]
	_ = x[CommandTypeDecryptPkcs1-73]
	_ = x[CommandTypeExportWrapped-74]
	_ = x[CommandTypeImportWrapped-75]
	_ = x[CommandTypePutWrapKey-76]
	_ = x[CommandTypeGetLogs-77]
	_ = x[CommandTypeGetObjectInfo-78]
	_ = x[CommandTypePutOption-79]
	_ = x[CommandTypeGetOption-80]
	_ = x[CommandTypeGetPseudoRandom-81]
	_ = x[CommandTypePutHMACKey-82]
	_ = x[CommandTypeHMACData-83]
	_ = x[CommandTypeGetPubKey-84]
	_ = x[CommandTypeSignDataPss-85]
	_ = x[CommandTypeSignDataEcdsa-86]
	_ = x[CommandTypeDecryptEcdh-87]
	_ = x[CommandTypeDeriveEcdh-87]
	_ = x[CommandTypeDeleteObject-88]
	_ = x[CommandTypeDecryptOaep-89]
	_ = x[CommandTypeGenerateHMACKey-90]
	_ = x[CommandTypeGenerateWrapKey-91]
	_ = x[CommandTypeVerifyHMAC-92]
	_ = x[CommandTypeOTPDecrypt-96]
	_ = x[CommandTypeOTPAeadCreate-97]
	_ = x[CommandTypeOTPAeadRandom-98]
	_ = x[CommandTypeOTPAeadRewrap-99]
	_ = x[CommandTypeAttestAsymmetric-100]
	_ = x[CommandTypePutOTPAeadKey-101]
	_ = x[CommandTypeGenerateOTPAeadKey-102]
	_ = x[CommandTypeSetLogIndex-103]
	_ = x[CommandTypeWrapData-104]
	_ = x[CommandTypeUnwrapData-105]
	_ = x[CommandTypeSignDataEddsa-106]
	_ = x[CommandTypeSetBlink-107]
	_ = x[CommandTypeChangeAuthenticationKey-108]
	_ = x[CommandTypeDecryptAesCbc-113]
	_ = x[CommandTypeEncryptAesCbc-114]
}

const (
	_CommandType_name_0 = "LogCommandTypeBootEcho"
	_CommandType_name_1 = "CreateSessionAuthenticateSessionSessionMessageDeviceInfo"
	_CommandType_name_2 = "Reset"
	_CommandType_name_3 = "CloseSessionStorageStatusPutOpaqueGetOpaquePutAuthKeyPutAsymmetricGenerateAsymmetricKeySignDataPkcs1ListObjectsDecryptPkcs1ExportWrappedImportWrappedPutWrapKeyGetLogsGetObjectInfoPutOptionGetOptionGetPseudoRandomPutHMACKeyHMACDataGetPubKeySignDataPssSignDataEcdsaDecryptEcdhDeleteObjectDecryptOaepGenerateHMACKeyGenerateWrapKeyVerifyHMAC"
	_CommandType_name_4 = "OTPDecryptOTPAeadCreateOTPAeadRandomOTPAeadRewrapAttestAsymmetricPutOTPAeadKeyGenerateOTPAeadKeySetLogIndexWrapDataUnwrapDataSignDataEddsaSetBlinkChangeAuthenticationKey"
	_CommandType_name_5 = "DecryptAesCbcEncryptAesCbc"
	_CommandType_name_6 = "LogCommandTypeReset"
)

var (
	_CommandType_index_0 = [...]uint8{0, 18, 22}
	_CommandType_index_1 = [...]uint8{0, 13, 32, 46, 56}
	_CommandType_index_3 = [...]uint16{0, 12, 25, 34, 43, 53, 66, 87, 100, 111, 123, 136, 149, 159, 166, 179, 188, 197, 212, 222, 230, 239, 250, 263, 274, 286, 297, 312, 327, 337}
	_CommandType_index_4 = [...]uint8{0, 10, 23, 36, 49, 65, 78, 96, 107, 115, 125, 138, 146, 169}
	_CommandType_index_5 = [...]uint8{0, 13, 26}
)

func (i CommandType) String() string {
	switch {
	case i <= 1:
		return _CommandType_name_0[_CommandType_index_0[i]:_CommandType_index_0[i+1]]
	case 3 <= i && i <= 6:
		i -= 3
		return _CommandType_name_1[_CommandType_index_1[i]:_CommandType_index_1[i+1]]
	case i == 8:
		return _CommandType_name_2
	case 64 <= i && i <= 92:
		i -= 64
		return _CommandType_name_3[_CommandType_index_3[i]:_CommandType_index_3[i+1]]
	case 96 <= i && i <= 108:
		i -= 96
		return _CommandType_name_4[_CommandType_index_4[i]:_CommandType_index_4[i+1]]
	case 113 <= i && i <= 114:
		i -= 113
		return _CommandType_name_5[_CommandType_index_5[i]:_CommandType_index_5[i+1]]
	case i == 255:
		return _CommandType_name_6
	default:
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
